name: CI Engine

on:
  pull_request:
    branches:
      - main
    paths:
      - "engine/**"

defaults:
  run:
    working-directory: ./engine

env:
  GOPRIVATE: "github.com/goofr-group"

jobs:
  ssh:
    uses: ./.github/workflows/ssh.yml
    secrets: inherit

  lint:
    runs-on: ubuntu-latest
    needs: ssh

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: make vendor

      - name: Run lint
        run: make lint

  build:
    runs-on: ubuntu-latest
    needs: ssh

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: make vendor

      - name: Run build
        run: make build
