name: CI Engine

on:
  pull_request:
    branches:
      - main
    paths:
      - "engine/**"

defaults:
  run:
    working-directory: ./engine

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: make mod

      - name: Run lint
        run: make lint

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: make mod

      - name: Run build
        run: make build
