name: CI Engine

on:
  pull_request:
    branches:
      - main
    paths:
      - "engine/**"

defaults:
  run:
    working-directory: ./engine

env:
  GOPRIVATE: "github.com/goofr-group"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Set up git ssh instead of https
        run: git config --global url."git@github.com:goofr-group".insteadOf https://github.com/goofr-group

      - name: Set up ssh keys
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.SSH_GO_MATH }}" > ~/.ssh/go-math
          echo "${{ secrets.SSH_PHYSICS_ENGINE }}" > ~/.ssh/physics-engine
          echo "${{ secrets.SSH_GAME_ENGINE }}" > ~/.ssh/game-engine

          cat >>~/.ssh/config <<END
          Host github.com:GOOFR-Group/go-math.git
            Hostname github.com:GOOFR-Group
            User git
            IdentityFile ~/.ssh/go-math
            IdentitiesOnly yes

          Host github.com:GOOFR-Group/physics-engine.git
            Hostname github.com:GOOFR-Group
            User git
            IdentityFile ~/.ssh/physics-engine
            IdentitiesOnly yes

          Host github.com:GOOFR-Group/game-engine.git
            Hostname github.com:GOOFR-Group
            User git
            IdentityFile ~/.ssh/game-engine
            IdentitiesOnly yes
          END

          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval $(ssh-agent -s) > /dev/null

          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV

      - name: Install dependencies
        run: make vendor

      - name: Run lint
        run: make lint

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: make vendor

      - name: Run build
        run: make build
