name: CI UI

on:
  pull_request:
    branches:
      - main
    paths:
      - "ui/**"

defaults:
  run:
    working-directory: ./ui

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
          cache-dependency-path: "./ui/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
          cache-dependency-path: "./ui/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run format
        run: npm run format
