name: CI UI

on:
  pull_request:
    branches:
      - main
    paths:
      - "ui/**"

defaults:
  run:
    working-directory: ./ui

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./ui/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

  format:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./ui/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run format
        run: npm run format
