name: Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Set up git ssh instead of https
        run: |
          git config --global url."git@go-math:goofr-group/go-math".insteadOf https://github.com/goofr-group/go-math
          git config --global url."git@physics-engine:goofr-group/physics-engine".insteadOf https://github.com/goofr-group/physics-engine
          git config --global url."git@game-engine:goofr-group/game-engine".insteadOf https://github.com/goofr-group/game-engine

      - name: Set up ssh keys
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.SSH_GO_MATH }}" > ~/.ssh/go-math
          echo "${{ secrets.SSH_PHYSICS_ENGINE }}" > ~/.ssh/physics-engine
          echo "${{ secrets.SSH_GAME_ENGINE }}" > ~/.ssh/game-engine
          chmod 600 ~/.ssh/*

          cat >>~/.ssh/config <<END
          Host go-math
            Hostname github.com
            IdentityFile ~/.ssh/go-math

          Host physics-engine
            Hostname github.com
            IdentityFile ~/.ssh/physics-engine

          Host game-engine
            Hostname github.com
            IdentityFile ~/.ssh/game-engine
          END

          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval $(ssh-agent -s) > /dev/null

      - name: Build distributable
        run: make build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jump-master
          path: ./dist
